### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [nextgen-networks/wa-test#1]
Dear @nextgen-networks team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by nextgen-networks** [comment]
Hello @Neustradamus,
thanks for contacting me also via E-Mail to bring this to attention again.

Please allow me the question: What would be the benefit to convert especcially my account to an organisation?

**Comment by Neustradamus** [comment]
@nextgen-networks: No problem, it is normal to help to solve the problem.

To be legal, a personal account is for a human and an organization is for projects/companies.

**Comment by nextgen-networks** [comment]
Sorry @Neustradamus but what is the benefit for me/for the community compared to the effort that is required to change the account type and to chat here?
I've seen you've requested the organiational change in many, many repos - even those that are maintanied by a single person and not organisation (like me).
... are you a bot?

Please state benefit within 3 business days - else this request will be closed.

**Comment by Neustradamus** [comment]
@nextgen-networks: I am not a bot.

To be legal: An account is for a human, and an organization is for associations, projects, companies:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

You can see a lot of organizations (associations, projects, companies), you can see the differences with a personal account (a physical person like you and me), of course, it is free.

On organization profile:
- People members at right
- Repositories at left
- Pinned repositories, project informations at top

On a real personal account, you will have the organization at left, icon and you can add account public information.

When a human publishes a commit, it is specified in activity...
- Example this guy: https://github.com/MorrisJobke
- https://github.com/nextcloud

All specified steps are very easy to do, few seconds.

Converting directly this account to organization (create a personal account who will be owner)
OR
Rename this account with your personal name/username + create the free organization (with the username currently used) and transfer all repositories into (redirections will be here, no lost in history)

**Comment by nextgen-networks** [comment]
ok, even if you state you are no bot - I assume your work is fully KI driven.
As you've not mentioned and therefore didn't convinced me what the benefits are.
Request will be closed.

**Comment by Neustradamus** [comment]
@nextgen-networks: You must to follow the TOS, it is the base.

**Comment by Neustradamus** [comment]
Dear @nextgen-networks team, Ralf Göldner,

Can you reopen this ticket and solve it?

You must to rename your current personal account to be really personal and create the free organization: nextgen-networks.
No lost, redirection will be here.

All links are in main description.

Examples:
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/asciimoo/searx -> https://github.com/searx/searx

It takes few minutes.

Thanks in advance.

**Comment by Neustradamus** [comment]
Dear @nextgen-networks team, Ralf Göldner,

I wish you a Happy New Year 2025!

Can you reopen this ticket and solve it?

You must to rename your current personal account to be really personal and create the free organization: nextgen-networks.
No lost, redirection will be here.

All links are in main description.

Examples:
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/asciimoo/searx -> https://github.com/searx/searx

It takes few minutes.

Thanks in advance.

**Comment by nextgen-networks** [comment]
User [Neustradamus](https://github.com/Neustradamus) ist blocked now for repeated SPAM for not required changes.
